language: minimal

script: bash ./deploy.sh

branches:
  only:
  - master

git:
  depth: 9999999

env:
  global:
  - ENCRYPTION_LABEL: "d8f0b56241d0"
  - COMMIT_AUTHOR_EMAIL: "wenzhixin2010@gmail.com"

sudo: false
